### ISSUE TITLE
Work Order Classes

### ISSUE THREAD

**Issue by dianecawley** [Acumatica/CMMS-Lite#4]
Create and/or Update the Work Order Class screen per the Functional Spec

**Comment by lekker-solutions** [comment]
This matches the functional spec @BrianMRO @jvanhoesen I will just add a entry point list

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/59847010/205374921-52b84132-a5bb-4171-903c-c45de3afad51.png">
