### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by dianecawley** [Acumatica/CMMS-Lite#5]
Create and/or Update the Measurements screen per the Functional Spec

**Comment by lekker-solutions** [comment]
Measurements changed to a listview @jvanhoesen @BrianMRO, functional spec has no other fields

<img width="576" alt="image" src="https://user-images.githubusercontent.com/59847010/205377047-87769ce8-4dbb-44e7-a2f3-c4c3aa205f4c.png">
