### ISSUE TITLE
Equipment Master - feature/004-EquipmentMaint

### ISSUE THREAD

**Issue by dianecawley** [Acumatica/CMMS-Lite#7]
Create and/or Update the Equipment Master screen per the Functional Spec

**Comment by anaxetogrind** [comment]
As per the conversation on 10/7 to add benefits for insurance tracking we should add the fields below as opposed to further go down the rabbit hole of adding which WO resolve the issue. As multiple WO could be involve as well as other implemented solutions.
WO204000 
      Failure Mode Tab
	IsMitigated bool
        MitigationDescription string

**Comment by anaxetogrind** [comment]
As per the conversation on 10/7 should show Created and Scheduled dates from the WO on the Work Order History Tab
WO204000
Work Order History Tab
Display the Created and Scheduled dates from the associated WO's
